apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angukar
        image: samk101/angular
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 20
          
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 20
        volumeMounts:
        - mountPath: /mnt
          name: angukar-data
      volumes:
      - name: angukar-data
        persistentVolumeClaim:
          claimName: angukar-vol
          
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: angukar-vol
spec:
 
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
    storage: 3Gi

---
apiVersion: v1
kind: Service
metadata: 
  name: angularsvc
spec:
  selector:
    app: angular
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer  

